### ISSUE TITLE
My YouTube channel

### ISSUE THREAD

**Issue by nikhilkumarsingh** [IlianIliev/python-courses#2]
Hi there!
I have been making videos on various Python topics lately.
My YouTube channel : [Indian Pythonista](https://youtube.com/IndianPythonista)
I would like to get my playlist [Intermediate Python](https://www.youtube.com/watch?v=SlrLZ1no08A&list=PLyb_C2HpOQSDJnnaz7vA8s5ssW7LjcWuH) listed on your guide.

In which section should I put it?

**Comment by IlianIliev** [comment]
Looks to me like it should go in the tutorial section

**Comment by IlianIliev** [comment]
Added in #7
