### ISSUE TITLE
tutos Flask

### ISSUE THREAD

**Issue by JulienParis** [IlianIliev/python-courses#4]
There's a guy I follow on youtube making very simple-to-understand tutos about Python and Flask : Pretty printed / https://www.youtube.com/channel/UC-QDfvrRIDB6F0bIO4I4HkQ/videos

**Comment by JulienParis** [comment]
Another one I used a lot : Sentdex / https://www.youtube.com/user/sentdex

**Comment by IlianIliev** [comment]
Resolved as part of #7
